Fix logical negation for leap year filtering
Ok this works now, however this seasonal subsetting no longer works somehow:
```
(RAiDER) [ssangha@trappist all]$ raiderStats.py --file "GNSS_WM_localtime06_Combined_delays_stations_over50.csv" -w Residual/stats_maps_localtime06_50mintime/raiderstats_output_winter -ti "2016-01-01 2025-12-31" -si '12-21 03-21' --cpus all -verbose -grid_to_raster -b '-90 90 -180 180' -sp 1 -figdpi 600 -grid_delay_mean -grid_delay_stdev -cb "-6 6" -u 'cm' -c ZTD_minus_RAiDER -oe 0.005 -fmt 'pdf' -tl
***Stats Function:***
Traceback (most recent call last):
  File "/u/trappist-r0/ssangha/conda_installation/miniforge/miniforge/envs/RAiDER/bin/raiderStats.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "/u/trappist-r0/ssangha/conda_installation/miniforge/miniforge/RAiDER/tools/RAiDER/cli/statsPlot.py", line 3474, in main
    stats_analyses(
    ~~~~~~~~~~~~~~^
        inps.fname,
        ^^^^^^^^^^^
    ...<42 lines>...
        inps.variogram_errlimit,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/u/trappist-r0/ssangha/conda_installation/miniforge/miniforge/RAiDER/tools/RAiDER/cli/statsPlot.py", line 2905, in stats_analyses
    df_stats = RaiderStats(
        fname,
    ...<27 lines>...
        phaseamp_per_station,
    )
  File "/u/trappist-r0/ssangha/conda_installation/miniforge/miniforge/RAiDER/tools/RAiDER/cli/statsPlot.py", line 1289, in __init__
    self.create_DF()
    ~~~~~~~~~~~~~~^^
  File "/u/trappist-r0/ssangha/conda_installation/miniforge/miniforge/RAiDER/tools/RAiDER/cli/statsPlot.py", line 1469, in create_DF
    (not self.df['Date'].dt.is_leap_year)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/trappist-r0/ssangha/conda_installation/miniforge/miniforge/envs/RAiDER/lib/python3.13/site-packages/pandas/core/generic.py", line 1580, in __nonzero__
    raise ValueError(
    ...<2 lines>...
    )
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```